          <hr />
          <div class="deployment-checklist-wrapper">
            <div class="deployment-checklist" data-spy="affix" data-offset-top="141">
              <h2 class="h3">Deployment Checklist</h2>
              <p class="deployment-steps-status"><a data-toggle="collapse" href="#deployment-steps" aria-expanded="true" aria-controls="deployment-steps">3 of 4 Steps Completed</a></p>
              <ul id="deployment-steps" class="collapse in">
                <li class="complete">Register Nodes</li>
                <li class="complete">Configure Networks</li>
                <li class="complete">Configure Roles</li>
                <li class="active">Assign Roles
                  <ul>
                    <li>1 Controller Needed</li>
                    <li>1 Compute Needed</li>
                    <li>1 Storage Needed</li>
                  </ul>
                </li>
              </ul>
              <button class="btn btn-default btn-primary" type="submit" disabled="disabled">Verify and Deploy</button>
            </div>
          </div>