          <hr />
          <div class="deployment-checklist-wrapper">
            <div class="deployment-checklist" data-spy="affix" data-offset-top="141">
              <h2 class="h3">Ready to Deploy</h2>
              <p class="deployment-steps-status"><a data-toggle="collapse" href="#deployment-steps" aria-expanded="true" aria-controls="deployment-steps">4 of 4 Steps Completed</a></p>
              <ul id="deployment-steps" class="collapse in">
                <li class="complete">Register Nodes</li>
                <li class="complete">Configure Roles</li>
                <li class="complete">Assign Roles
                  <ul>
                    <li class="complete">1 Controller Needed</li>
                    <li class="complete">1 Compute Needed</li>
                    <li class="complete">1 Block Storage Needed</li>
                  </ul>
                </li>
              </ul>
              <button class="btn btn-default btn-primary" type="submit">Verify and Deploy</button>
            </div>
          </div>