<div class="modal fade" id="global-configuration" tabindex="-1" role="dialog" aria-labelledby="global-configuration-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          <span class="pficon pficon-close"></span>
        </button>
        <h2 class="modal-title" id="global-configuration-label">Edit Global Configuration</h2>
      </div>
      <div class="modal-body">
        [Edit Global Configuration]
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary">Save</button>
      </div>
    </div>
  </div>
</div>