    <nav class="navbar navbar-default navbar-pf" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          <img src="../dist/img/brand.svg" alt="Red Hat&reg; Openstack Manager" />
        </a>
      </div>
      <div class="collapse navbar-collapse navbar-collapse-1">
        <ul class="nav navbar-nav navbar-utility">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="pficon pficon-user"></span>
              Brian Johnson <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="#">Link</a>
              </li>
              <li>
                <a href="#">Another link</a>
              </li>
              <li>
                <a href="#">Something else here</a>
              </li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-primary">
          <li class="active">
            <a href="basic.html" class="active">Overview</a>
          </li>
          <li>
            <a href="bootstrap-treeview-2.html">Service Configuration</a>
          </li>
          <li>
            <a href="dashboard.html">Deployment Roles</a>
          </li>
          <li>
            <a href="form.html">Nodes</a>
          </li>
          <li>
            <a href="tab.html">Ready State Profiles</a>
          </li>
          <li>
            <a href="typography-2.html">Provisioning Images</a>
          </li>
          <li>
            <a href="typography-2.html">Deployment Log</a>
          </li>
        </ul>
      </div>
    </nav>