    <div class="row title-bar">
      <div class="col-sm-7 col-md-8">
        <h1>My Openstack Deployment</h1>
        <a href="#" class="edit-config" data-toggle="modal" data-target="#global-configuration">Edit Global Configuration</a>
      </div>
      <div class="col-sm-5 col-md-4 buttons">
        <a class="btn btn-default" href="#" role="button" data-toggle="modal" data-target="#register-nodes"><i class="fa fa-plus"></i> Register Nodes</a>
        <a class="btn btn-default" href="#" role="button" data-toggle="modal" data-target="#configure-networks">Configure Networks</a>
      </div>
    </div>