    <div class="row title-bar">
      <div class="col-sm-7 col-md-8">
        <h1 data-toggle="tooltip" data-placement="bottom" data-trigger="click" title="Foo.">My Openstack Deployment</h1>
        <a href="#" class="edit-config">Edit Global Configuration</a>
      </div>
      <div class="col-sm-5 col-md-4 buttons">
        <a class="btn btn-default" href="#" role="button"><i class="fa fa-plus"></i> Register Nodes</a>
        <a class="btn btn-default" href="#" role="button">Configure Networks</a>
      </div>
    </div>